version: 0.2

phases:
   install:
      runtime-versions:
         nodejs: 8
      commands:
       - echo "install"
   pre_build:
      commands:
       - echo "pre_build nothing"
   build:
      commands:
       - echo "build nothing"
   post_build:
      commands:
       - echo "build completed on `date`"
       - aws update-function-code --function-name lambda_edge --zip-file lambda_edge.zip
