version: 0.2

phases:
   install:
      runtime-versions:
         nodejs: 8
      commands:
       - echo "Not install"
   pre_build:
      commands:
       - echo "zip -> lambda function"
       - zip lambda_edge.zip lambda_edge.js
   build:
      commands:
       - echo "build nothing"
   post_build:
      commands:
       - echo "build completed on `date`"

artifacts:
   files:
    - "**/*"
   discard-paths: yes
