version: 0.2

phases:
   install:
      runtime-versions:
         java: openjdk8
      commands:
       - echo Install Start
       - zip lambda_edge_test.zip lambda_edge.js
#       - aws s3 cp s3://test-ray-credential/credential/credentials .
   build:
      commands:
       - echo Build started on 'date'
       - cp -a /root/pipeline pipeline
       - cp -a lambda_edge_test.zip /pipeline/lambda_edge_test.zip
       - cd pipeline
       - terraform init
       - terraform plan -lock=false
       - terraform apply -auto-approve -lock=false
   post_build:
      commands:
       - echo build compeleted on 'date'
artifacts:
   files:
    - '**/*'
   name: arti-$(date+%Y-%m-%d)
