version: 0.2

phases:
   install:
      runtime-versions:
         nodejs: 8
      commands:
       - echo "install"
       - export BUCKET=terraform-ray-infra-tf-us-east-1
       - aws cloudformation package --template-file template.yaml --s3-bucket $BUCKET --output-template-file outputtemplate.yaml
   pre_build:
      commands:
       - echo "pre_build nothing"
   build:
      commands:
       - echo "build nothing"
   post_build:
      commands:
       - echo "build completed on `date`"

artifacts:
   files:
    - template.yaml
    - outputtemplate.yaml
