version: 0.2

phases:
   install:
      runtime-versions:
         java: openjdk8
      commands:
       - echo Install Start
       - zip lambda_edge_test.zip lambda_edge.js
#       - aws s3 cp s3://test-ray-credential/credential/credentials .
       - terraform init
   build:
      commands:
       - echo Build started on 'date'
       - terraform plan
       - terraform apply -auto-approve
   post_build:
      commands:
       - echo build compeleted on 'date'
       - ls -al
artifacts:
   files:
    - '**/*'
   name: arti-$(date+%Y-%m-%d)
